export default function useDespesasData() {
  // mock data
  const data = [
    {
      key: '1',
      ano: 2025,
      mes: 'Janeiro',
      empenho: '1-2025',
      beneficiario: 'CÂMARA MUNICIPAL DE IGUARACY',
      cpfCnpj: '11.464.385/0001-64',
      historico:
        'Repasse dos subsídios dos vereadores desta casa legislativa, correspondente ao exercício de 2025.',
      valorEmpenhado: 'R$ 113.800,00',
      dataEmpenho: '02/01/2025',
      liquidacao: 94833.33,
      dataPagamento: '20/01/2025',
      pagamento: 'R$ 94.833,33',
      licitacao: 'SEM LICITAÇÃO',
      elemento: 'Pessoal Civil',
      funcao: 'Legislativa',
      subFuncao: 'Ação Legislativa',
      recursos: 'Outros Recursos não Vinculados',
      grupoNatureza: 'Pessoal e Encargos Sociais',
      categoriaEconomica: 'Despesa Corrente',
      unidadeOrcamentaria: 'Câmara Municipal de Iguaracy',
    },
    {
      key: '2',
      ano: 2025,
      mes: 'Janeiro',
      empenho: '1-2025',
      beneficiario: 'CÂMARA MUNICIPAL DE IGUARACY',
      cpfCnpj: '11.464.385/0001-64',
      historico:
        'Repasse dos subsídios dos vereadores desta casa legislativa, correspondente ao exercício de 2025.',
      valorEmpenhado: 'R$ 113.800,00',
      dataEmpenho: '02/01/2025',
      liquidacao: 94833.33,
      dataPagamento: '20/01/2025',
      pagamento: 'R$ 94.833,33',
      licitacao: 'SEM LICITAÇÃO',
      elemento: 'Pessoal Civil',
      funcao: 'Legislativa',
      subFuncao: 'Ação Legislativa',
      recursos: 'Outros Recursos não Vinculados',
      grupoNatureza: 'Pessoal e Encargos Sociais',
      categoriaEconomica: 'Despesa Corrente',
      unidadeOrcamentaria: 'Câmara Municipal de Iguaracy',
    },
    {
      key: '3',
      ano: 2025,
      mes: 'Janeiro',
      empenho: '1-2025',
      beneficiario: 'CÂMARA MUNICIPAL DE IGUARACY',
      cpfCnpj: '11.464.385/0001-64',
      historico:
        'Repasse dos subsídios dos vereadores desta casa legislativa, correspondente ao exercício de 2025.',
      valorEmpenhado: 'R$ 113.800,00',
      dataEmpenho: '02/01/2025',
      liquidacao: 94833.33,
      dataPagamento: '20/01/2025',
      pagamento: 'R$ 94.833,33',
      licitacao: 'SEM LICITAÇÃO',
      elemento: 'Pessoal Civil',
      funcao: 'Legislativa',
      subFuncao: 'Ação Legislativa',
      recursos: 'Outros Recursos não Vinculados',
      grupoNatureza: 'Pessoal e Encargos Sociais',
      categoriaEconomica: 'Despesa Corrente',
      unidadeOrcamentaria: 'Câmara Municipal de Iguaracy',
    },
  ]

  return {
    data,
  }
}
